run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/yuriiwanchev/banner-rotation-service/internal/entities
          - github.com/yuriiwanchev/banner-rotation-service/internal/models
          - github.com/yuriiwanchev/banner-rotation-service/internal/logic/bandit
          - github.com/segmentio/kafka-go
          - github.com/yuriiwanchev/banner-rotation-service/internal/api
          - github.com/yuriiwanchev/banner-rotation-service/internal/kafka
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - github.com/orlangure/gnomock
          - github.com/orlangure/gnomock/preset/kafka
          - github.com/yuriiwanchev/banner-rotation-service/internal/repository
          - github.com/yuriiwanchev/banner-rotation-service/internal/repository/slotbannersrepository
          - github.com/yuriiwanchev/banner-rotation-service/internal/repository/slotrepository
          - github.com/yuriiwanchev/banner-rotation-service/internal/repository/bannersrepository
          - github.com/yuriiwanchev/banner-rotation-service/internal/repository/usergrouprepository
          - github.com/yuriiwanchev/banner-rotation-service/internal/repository/statisticrepository

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace