version: '3.8'
services:
  banner-rotation-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=banner_events
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    depends_on:
      - kafka
  kafka:
    image: confluentinc/cp-kafka:5.4.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  statistic-consumer:
    build: ../statistic-consumer/
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=banner_events
    depends_on:
      - zookeeper
      - banner-rotation-service

