version: '3.8'
services:
  banner-rotation-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/banner_rotation_db?sslmode=disable
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=banner_events
    depends_on:
      - zookeeper
      - db
      - kafka

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banner_rotation_db
    ports:
      - "5432:5432"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:5.4.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  statistic-consumer:
    build: ../statistic-consumer/
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=banner_events
    depends_on:
      - zookeeper
      - banner-rotation-service

