name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Check out code
      uses: actions/checkout@v4

    - name: Linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.59.1
        working-directory: banner-rotation-service
