name: Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Check out code
      uses: actions/checkout@v4

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Save Go environment
      id: save-go-env
      run: echo "GO_ENV=$(go env GOPATH)" >> $GITHUB_ENV

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Load Go environment
      run: echo "$GO_ENV" > $GITHUB_ENV

    - name: Linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.59.1
        working-directory: banner-rotation-service

  tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Load Go environment
      run: echo "$GO_ENV" > $GITHUB_ENV

    - name: Run unit tests
      run: go test -race -count 100 ./...
      working-directory: banner-rotation-service

  build:
    needs: setup
    needs: tests
    needs: lint
    runs-on: ubuntu-latest

    steps:
    - name: Load Go environment
      run: echo "$GO_ENV" > $GITHUB_ENV

    - name: Build binary
      run: go build -o banner-rotation-service ./cmd
      working-directory: banner-rotation-service

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: banner-rotation-service
        path: ./banner-rotation-service
