name: Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Check out code
      uses: actions/checkout@v4

    - name: Linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.59.1
        working-directory: banner-rotation-service

  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run unit tests
      run: go test -race -count 100 ./...
      working-directory: banner-rotation-service

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build binary
      run: go build -o banner-rotation-service ./cmd
      working-directory: banner-rotation-service

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: banner-rotation-service
        path: ./banner-rotation-service
