name: Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.22'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
        sudo mv ./bin/golangci-lint /usr/local/bin/

    - name: Run golangci-lint
      run: |
        cd banner-rotation-service
        golangci-lint run --timeout 10m

    - name: Run unit tests
      run: go test -race -count 100 ./...

    - name: Build binary
      run: go build -o banner-rotation-service ./cmd
