name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run unit tests
      run: go test -race -count 100 ./...
      working-directory: banner-rotation-service
